name: questionnaires
description: A Flutter app with psychological questionnaires.
version: 1.0.0+1
author: Joanna Laskowska

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  grouped_buttons: ^1.0.4
  dots_indicator: ^1.1.0
  flutter_launcher_icons: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/questionnaires/

flutter_icons:
  android: "ic_launcher" 
  ios: true
  image_path: "assets_dev/app_icon.png"